FROM oven/bun:1.0.29

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

# Install dependencies without optional packages (like Cypress)
RUN bun install --no-optional

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
